---
# tasks file for deploy_nginx
- name: Install Nginx
  apt:
    name: nginx
    state: latest
  when: ansible_os_family == "Debian"

- name: Copy all files from ./MyWebSite to server
  copy:
    src: "{{ item }}"
    dest: "{{ dst_folder }}"
    mode: 0555
  with_fileglob: "/*.html"
  notify: Restart nginx

- name: Generating index.html
  template:
    src: "index.j2"
    dest: "{{dst_folder}}/index.html"
    mode: 0555
  notify: Restart nginx